// Code generated by goctl. DO NOT EDIT!

package paymentqueue

import (
	"fmt"
	"strconv"

	"github.com/zeromicro/go-zero/core/stores/redis"
)

var (
	cacheRPaymentQueuePrefix = "cache:rPaymentQueue"
)

type (
	rPaymentQueueModel interface {
		Insert(data *RPaymentQueue) (error)
		FindOne(orderId int64) (*int, error)
		Delete(orderId int64) (bool, error)
	}

	defaultRPaymentQueueModel struct {
		conn redis.Redis
		table string
	}

	RPaymentQueue struct {
		OrderId int64  `db:"order_id"`
		DueDate string `db:"due_date"`
	}
)

func newRPaymentQueueModel(c redis.RedisConf) *defaultRPaymentQueueModel {
	return &defaultRPaymentQueueModel{
		conn:       *c.NewRedis(),
		table:      "`r_payment_queue`",
	}
}

func (m *defaultRPaymentQueueModel) Insert(data *RPaymentQueue) (error) {
	err := m.conn.Hset(cacheRPaymentQueuePrefix, strconv.FormatInt(data.OrderId, 10), data.DueDate)
	return err
}

func (m *defaultRPaymentQueueModel) FindOne(orderId int64) (*int, error) {
	ret, err := m.conn.Hget(cacheRPaymentQueuePrefix, strconv.FormatInt(orderId, 10))
	switch err {
	case nil:
		ret_int, err := strconv.Atoi(ret)
		if err != nil {
			return nil, err
		} else {
			return &ret_int, nil
		}
	case redis.Nil:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRPaymentQueueModel) Delete(orderId int64) (bool, error) {
	ret, err := m.conn.Hdel(cacheRPaymentQueuePrefix, strconv.FormatInt(orderId, 10))
	return ret, err
}

func (m *defaultRPaymentQueueModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheRPaymentQueuePrefix, primary)
}

func (m *defaultRPaymentQueueModel) tableName() string {
	return m.table
}
