// Code generated by goctl. DO NOT EDIT!

package schedule

import (
	"fmt"
	"strconv"

	"github.com/zeromicro/go-zero/core/stores/redis"
)

var (
	cacheBScheduleContractorIdPrefix = "cache:bSchedule:contractId:"
)

type (
	bScheduleModel interface {
		Insert(data *BSchedule) (int, error)
		FindOne(contractorId int64, orderId int64) (int, error)
		List(contractorId int64) (*[]int64, error)
		Delete(contractorId int64, orderId int64) (int, error)
		DeleteAll(contractorId int64) (int, error)
	}

	defaultBScheduleModel struct {
		conn redis.Redis
		table string
	}

	BSchedule struct {
		ContractorId int64 `db:"contractor_id"`
		OrderId      int64 `db:"order_id"`
	}
)

func newBScheduleModel(c redis.RedisConf) *defaultBScheduleModel {
	return &defaultBScheduleModel{
		conn:       *c.NewRedis(),
		table:      "`b_schedule`",
	}
}

func (m *defaultBScheduleModel) Insert(data *BSchedule) (int, error) {
	bScheduleContractorIdKey := fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, data.ContractorId)
	ret, err := m.conn.Sadd(bScheduleContractorIdKey, data.OrderId)
	return ret, err
}

func (m *defaultBScheduleModel) FindOne(contractorId int64, orderId int64) (int, error) {
	bScheduleContractorIdKey := fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, contractorId)
	ret, _, err := m.conn.Sscan(bScheduleContractorIdKey, 0, strconv.FormatInt(orderId, 10), 1)
	
	if err != nil {
		return 0, err
	} else if len(ret) == 0 {
		return 0, ErrNotFound
	}
	return 1, nil
}

func (m *defaultBScheduleModel) List(contractorId int64) (*[]int64, error) {
	bScheduleContractorIdKey := fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, contractorId)
	ret, err := m.conn.Smembers(bScheduleContractorIdKey)

	switch err {
	case nil:
		var resp []int64
		for _, val := range ret{
			order_id, err := strconv.ParseInt(val, 10, 64)
			if err == nil {
				resp = append(resp, order_id)
			}
		}
		return &resp, nil
	default:
		return nil, err
	}
}

func (m *defaultBScheduleModel) Delete(contractorId int64, orderId int64) (int, error) {
	bScheduleContractorIdKey := fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, contractorId)
	ret, err := m.conn.Srem(bScheduleContractorIdKey, orderId)
	return ret, err
}

func (m *defaultBScheduleModel) DeleteAll(contractorId int64) (int, error) {
	bScheduleContractorIdKey := fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, contractorId)
	ret, err := m.conn.Del(bScheduleContractorIdKey)
	return ret, err
}

func (m *defaultBScheduleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBScheduleContractorIdPrefix, primary)
}

func (m *defaultBScheduleModel) tableName() string {
	return m.table
}
