// Code generated by goctl. DO NOT EDIT!

package customer

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bCustomerFieldNames          = builder.RawFieldNames(&BCustomer{})
	bCustomerRows                = strings.Join(bCustomerFieldNames, ",")
	bCustomerRowsExpectAutoSet   = strings.Join(stringx.Remove(bCustomerFieldNames, "`customer_id`", "`create_time`", "`update_time`"), ",")
	bCustomerRowsWithPlaceHolder = strings.Join(stringx.Remove(bCustomerFieldNames, "`customer_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheBCustomerCustomerIdPrefix = "cache:bCustomer:customerId:"
)

type (
	bCustomerModel interface {
		Insert(ctx context.Context, data *BCustomer) (sql.Result, error)
		FindOne(ctx context.Context, customerId int64) (*BCustomer, error)
		FindOnebyPhone(ctx context.Context, contactDetails string) (*BCustomer, error)
		Update(ctx context.Context, data *BCustomer) error
		Delete(ctx context.Context, customerId int64) error
	}

	defaultBCustomerModel struct {
		sqlc.CachedConn
		table string
	}

	BCustomer struct {
		CustomerId     int64  `db:"customer_id"`
		CustomerName   string `db:"customer_name"`
		CountryCode    string `db:"country_code"`
		ContactDetails string `db:"contact_details"`
	}
)

func newBCustomerModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultBCustomerModel {
	return &defaultBCustomerModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`b_customer`",
	}
}

func (m *defaultBCustomerModel) Insert(ctx context.Context, data *BCustomer) (sql.Result, error) {
	bCustomerCustomerIdKey := fmt.Sprintf("%s%v", cacheBCustomerCustomerIdPrefix, data.CustomerId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, bCustomerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CustomerName, data.CountryCode, data.ContactDetails)
	}, bCustomerCustomerIdKey)
	return ret, err
}

func (m *defaultBCustomerModel) FindOne(ctx context.Context, customerId int64) (*BCustomer, error) {
	bCustomerCustomerIdKey := fmt.Sprintf("%s%v", cacheBCustomerCustomerIdPrefix, customerId)
	var resp BCustomer
	err := m.QueryRowCtx(ctx, &resp, bCustomerCustomerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `customer_id` = ? limit 1", bCustomerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, customerId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBCustomerModel) FindOnebyPhone(ctx context.Context, contactDetails string) (*BCustomer, error) {
	bCustomerContactDetails := fmt.Sprintf("%s%v", "cache:bCustomer:contactDetails:", contactDetails)
	var resp BCustomer
	err := m.QueryRowCtx(ctx, &resp, bCustomerContactDetails, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `contact_details` = ? limit 1", bCustomerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, contactDetails)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBCustomerModel) Update(ctx context.Context, data *BCustomer) error {
	bCustomerCustomerIdKey := fmt.Sprintf("%s%v", cacheBCustomerCustomerIdPrefix, data.CustomerId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `customer_id` = ?", m.table, bCustomerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CustomerName, data.CountryCode, data.ContactDetails, data.CustomerId)
	}, bCustomerCustomerIdKey)
	return err
}

func (m *defaultBCustomerModel) Delete(ctx context.Context, customerId int64) error {
	bCustomerCustomerIdKey := fmt.Sprintf("%s%v", cacheBCustomerCustomerIdPrefix, customerId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `customer_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, customerId)
	}, bCustomerCustomerIdKey)
	return err
}

func (m *defaultBCustomerModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBCustomerCustomerIdPrefix, primary)
}

func (m *defaultBCustomerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? limit 1", bCustomerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBCustomerModel) tableName() string {
	return m.table
}
