// Code generated by goctl. DO NOT EDIT!

package orderdelay

import (
	"fmt"

	"github.com/zeromicro/go-zero/core/stores/redis"
)

var (
	cacheROrderDelayContractorIdPrefix = "cache:rOrderDelay:contractId:"
)

type (
	rOrderDelayModel interface {
		Insert(data *ROrderDelay) (error)
		FindOne(contractorId int64, orderId int64) (bool, error)
		Delete(contractorId int64, orderId int64) (int, error)
	}

	defaultROrderDelayModel struct {
		conn redis.Redis
		table string
	}

	ROrderDelay struct {
		ContractorId int64 `db:"contractor_id"`
		OrderId      int64 `db:"order_id"`
	}
)

func newROrderDelayModel(c redis.RedisConf) *defaultROrderDelayModel {
	return &defaultROrderDelayModel{
		conn:       *c.NewRedis(),
		table:      "`r_order_delay`",
	}
}

func (m *defaultROrderDelayModel) Insert(data *ROrderDelay) (error) {
	rOrderDelayContractorIdKey := fmt.Sprintf("%s%v:%v", cacheROrderDelayContractorIdPrefix, data.ContractorId, data.OrderId)
	err := m.conn.Set(rOrderDelayContractorIdKey, "decline")
	m.conn.Expire(rOrderDelayContractorIdKey, 86400)
	return err
}

func (m *defaultROrderDelayModel) FindOne(contractorId int64, orderId int64) (bool, error) {
	rOrderDelayContractorIdKey := fmt.Sprintf("%s%v:%v", cacheROrderDelayContractorIdPrefix, contractorId, orderId)
	ret, err := m.conn.Get(rOrderDelayContractorIdKey)
	if err != nil {
		return false, err
	} else if len(ret) == 0 {
		return false, ErrNotFound
	}
	return true, nil
}

func (m *defaultROrderDelayModel) Delete(contractorId int64, orderId int64) (int, error) {
	rOrderDelayContractorIdKey := fmt.Sprintf("%s%v:%v", cacheROrderDelayContractorIdPrefix, contractorId, orderId)
	ret, err := m.conn.Del(rOrderDelayContractorIdKey)
	return ret, err
}

func (m *defaultROrderDelayModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheROrderDelayContractorIdPrefix, primary)
}

func (m *defaultROrderDelayModel) tableName() string {
	return m.table
}
