// Code generated by goctl. DO NOT EDIT!

package customerpayment

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rCustomerPaymentFieldNames          = builder.RawFieldNames(&RCustomerPayment{})
	rCustomerPaymentRows                = strings.Join(rCustomerPaymentFieldNames, ",")
	rCustomerPaymentRowsExpectAutoSet   = strings.Join(stringx.Remove(rCustomerPaymentFieldNames, "`create_time`", "`update_time`"), ",")
)

type (
	rCustomerPaymentModel interface {
		Insert(ctx context.Context, data *RCustomerPayment) (sql.Result, error)
		FindOne(ctx context.Context, customerId int64, paymentId int64) (*RCustomerPayment, error)
		FindAllByCustomer(ctx context.Context, customerId int64) ([]*RCustomerPayment, error)
		Delete(ctx context.Context, customerId int64, paymentId int64) error
		DeleteByCustomer(ctx context.Context, customerId int64) error
	}

	defaultRCustomerPaymentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RCustomerPayment struct {
		CustomerId int64     `db:"customer_id"`
		PaymentId  int64     `db:"payment_id"`
		UpdateDate time.Time `db:"update_date"`
	}
)

func newRCustomerPaymentModel(conn sqlx.SqlConn) *defaultRCustomerPaymentModel {
	return &defaultRCustomerPaymentModel{
		conn:  conn,
		table: "`r_customer_payment`",
	}
}

func (m *defaultRCustomerPaymentModel) Insert(ctx context.Context, data *RCustomerPayment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, rCustomerPaymentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.PaymentId, data.UpdateDate)
	return ret, err
}

func (m *defaultRCustomerPaymentModel) FindOne(ctx context.Context, customerId int64, paymentId int64) (*RCustomerPayment, error) {
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? and `payment_id` = ? limit 1", rCustomerPaymentRows, m.table)
	var resp RCustomerPayment
	err := m.conn.QueryRowCtx(ctx, &resp, query, customerId, paymentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRCustomerPaymentModel) FindAllByCustomer(ctx context.Context, customerId int64) ([]*RCustomerPayment, error) {
	var resp []*RCustomerPayment

	query := fmt.Sprintf("select %s from %s where `customer_id` = ?", rCustomerPaymentRows, m.table)
	err := m.conn.QueryRowsCtx(ctx, &resp, query, customerId)

	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRCustomerPaymentModel) Delete(ctx context.Context, customerId int64, paymentId int64) error {
	query := fmt.Sprintf("delete from %s where `customer_id` = ? and `payment_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, customerId, paymentId)
	return err
}

func (m *defaultRCustomerPaymentModel) DeleteByCustomer(ctx context.Context, customerId int64) error {
	query := fmt.Sprintf("delete from %s where `customer_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, customerId)
	return err
}

func (m *defaultRCustomerPaymentModel) tableName() string {
	return m.table
}
