-- Service Item Initialize --
--  End of Lease Cleaning Standards --
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Studio", "End of Lease Cleaning - Studio. In a studio, the other living areas—kitchen, living room, and bedroom—are typically combined into one larger space.", 170);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Studio (with carpet)", "End of Lease Cleaning - Studio with carpet. In a studio, the other living areas—kitchen, living room, and bedroom—are typically combined into one larger space. (Combined with Carpet Steam Cleaning).", 220);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "1b1h1b", "End of Lease Cleaning - 1b1h1b. 1 Bedroom 1 Hall 1 Bathroom.", 200);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "1b1h1b (with carpet)", "End of Lease Cleaning - 1b1h1b with carpet. 1 Bedroom 1 Hall 1 Bathroom combined with Carpet Steam Cleaning.", 280);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "2b1h1b", "End of Lease Cleaning - 2b1h1b. 2 Bedroom 1 Hall 1 Bathroom.", 240);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "2b1h1b (with carpet)", "End of Lease Cleaning - 2b1h1b with carpet. 2 Bedroom 1 Hall 1 Bathroom combined with Carpet Steam Cleaning.", 360);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "2b1h2b", "End of Lease Cleaning - 2b1h2b. 2 Bedroom 1 Hall 2 Bathroom.", 280);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "2b1h2b (with carpet)", "End of Lease Cleaning - 2b1h2b with carpet. 2 Bedroom 1 Hall 2 Bathroom combined with Carpet Steam Cleaning.", 400);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "3b1h1b", "End of Lease Cleaning - 3b1h1b. 3 Bedroom 1 Hall 1 Bathroom.", 320);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "3b1h1b (with carpet)", "End of Lease Cleaning - 3b1h1b with carpet. 3 Bedroom 1 Hall 1 Bathroom combined with Carpet Steam Cleaning.", 450);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "3b1h2b", "End of Lease Cleaning - 3b1h2b. 3 Bedroom 1 Hall 2 Bathroom.", 360);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "3b1h2b (with carpet)", "End of Lease Cleaning - 3b1h2b with carpet. 3 Bedroom 1 Hall 2 Bathroom combined with Carpet Steam Cleaning.", 490);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b1h1b", "End of Lease Cleaning - 4b1h1b. 4 Bedroom 1 Hall 1 Bathroom.", 380);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b1h1b (with carpet)", "End of Lease Cleaning - 4b1h1b with carpet. 4 Bedroom 1 Hall 1 Bathroom combined with Carpet Steam Cleaning.", 530);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b1h2b", "End of Lease Cleaning - 4b1h2b. 4 Bedroom 1 Hall 2 Bathroom.", 400);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b1h2b (with carpet)", "End of Lease Cleaning - 4b1h2b with carpet. 4 Bedroom 1 Hall 2 Bathroom combined with Carpet Steam Cleaning.", 550);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b2h3b", "End of Lease Cleaning - 4b2h3b. 4 Bedroom 2 Hall 3 Bathroom.", 450);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "4b2h3b (with carpet)", "End of Lease Cleaning - 4b2h3b with carpet. 4 Bedroom 2 Hall 3 Bathroom combined with Carpet Steam Cleaning.", 600);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "5b2h3b", "End of Lease Cleaning - 5b2h3b. 5 Bedroom 2 Hall 3 Bathroom.", 500);
-- INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "5b2h3b (with carpet)", "End of Lease Cleaning - 5b2h3b with carpet. 5 Bedroom 2 Hall 3 Bathroom combined with Carpet Steam Cleaning.", 650);
-- End of Lease Cleaning Additions --
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Bedroom", "End of Lease Cleaning - Bedroom cleaning", 40);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Livingroom", "End of Lease Cleaning - Livingroom cleaning", 40);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Bathroom", "End of Lease Cleaning - Bathroom cleaning", 60);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Toilet", "End of Lease Cleaning - Toilet cleaning", 25);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Base Options", "Balcony", "End of Lease Cleaning - Balcony cleaning", 40);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Garage", "End of Lease Cleaning - Garage cleaning", 50);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Garden", "End of Lease Cleaning - Garden cleaning", 100);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Microwave", "End of Lease Cleaning - One Microwave cleaning", 15);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Refrigerator", "End of Lease Cleaning - One Refrigerato cleaningr", 50);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Dishwasher", "End of Lease Cleaning - One Dishwasher cleaning", 40);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Louver", "End of Lease Cleaning - Louver cleaning per piece", 20);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Windows Glass", "End of Lease Cleaning - Windows glass cleaning per piece", 15);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Windows Screen", "End of Lease Cleaning - Windows screen cleaning per piece", 15);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Air Conditioning Filter", "End of Lease Cleaning - Air Conditioning Filter cleaning per piece", 15);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Mildew on Wall", "End of Lease Cleaning - Mildew cleaning per Wall", 20);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Wall Stain", "End of Lease Cleaning - Wall Stain cleaning per face", 20);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Garbage Packing/hr", "End of Lease Cleaning - Garbage Packing per hour", 50);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Waste Transportation/cube", "End of Lease Cleaning - Waste Transportation per cubic meter", 150);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Pet Hair Cleaning", "End of Lease Cleaning - Pet Hair Cleaning", 80);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Carpet Stain", "End of Lease Cleaning - Carpet Stain cleaning", 80);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (1, "Additional Options", "Glass Glue Replacement", "End of Lease Cleaning - Glass Glue Replacement", 100);

-- Routine Cleaning Standards --
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (2, "Base Options", "Standard Plan(1p/2hr)", "Routine Cleaning- Standard Plan(2hr) with one professional cleaner in 2 hours working.", 110);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (2, "Base Options", "Standard Plan(2p/2hr)", "Routine Cleaning- Standard Plan(2hr) with two professional cleaner in 2 hours working.", 220);
-- Routine Cleaning Additions --
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (2, "Additional Options", "Additional Hour for 1p", "Routine Cleaning - Additional Hour for one professinal cleaner plan.", 55);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (2, "Additional Options", "Additional Hour for 2p", "Routine Cleaning - Additional Hour for two professinal cleaner plan.", 110);
INSERT INTO b_item (service_type, service_scope, service_name, service_description, service_price) values (2, "Additional Options", "Carpet Steam (One Room)", "Routine Cleaning  - Carpet Steam (One Room)", 80);
