// Code generated by goctl. DO NOT EDIT.

export interface VerifyCodeRequest {
	contact_details: string
}

export interface VerifyCodeResponse {
	code: string
	message: string
}

export interface LoginServiceRequest {
	contact_details: string
	verify_code: string
}

export interface LoginServiceResponse {
	code: string
	message: string
	access_token?: string
}

export interface LoginCustomerRequest {
	contact_details: string
	verify_code: string
}

export interface LoginCustomerResponse {
	code: string
	message: string
	access_token?: string
}

export interface CreateAddressRequest {
	address_details: string
	suburb: string
	postcode: string
	state_code: string
	country: string
}

export interface CreateAddressResponse {
	address_id: number
}

export interface UpdateAddressRequest {
	address_id: number
	address_details: string
	suburb: string
	postcode: string
	state_code: string
	country: string
}

export interface UpdateAddressResponse {
}

export interface RemoveAddressRequest {
	address_id: number
}

export interface RemoveAddressResponse {
}

export interface DetailAddressRequest {
	address_id: number
}

export interface DetailAddressResponse {
	address_id: number
	address_details: string
	suburb: string
	postcode: string
	state_code: string
	country: string
}

export interface ListAddressRequest {
}

export interface ListAddressResponse {
	items: Array<DetailAddressResponse>
}

export interface CreateCompanyRequest {
	company_name: string
	payment_id: number
	director_name: string
	contact_details: string
	registered_address: number
	deposite_rate: number
}

export interface CreateCompanyResponse {
	company_id: number
}

export interface UpdateCompanyRequest {
	company_id: number
	company_name: string
	payment_id: number
	director_name: string
	contact_details: string
	registered_address: number
	deposite_rate: number
}

export interface UpdateCompanyResponse {
}

export interface RemoveCompanyRequest {
	company_id: number
}

export interface RemoveCompanyResponse {
}

export interface DetailCompanyRequest {
	company_id: number
}

export interface DetailCompanyResponse {
	company_id: number
	company_name: string
	payment_id: number
	director_name: string
	contact_details: string
	registered_address: number
	deposite_rate: number
}

export interface ListCompanyRequest {
}

export interface ListCompanyResponse {
	items: Array<DetailCompanyResponse>
}

export interface CreateCustomerRequest {
	customer_name: string
	country_code: string
	contact_details: string
}

export interface CreateCustomerResponse {
	customer_id: number
}

export interface UpdateCustomerRequest {
	customer_id: number
	customer_name: string
	country_code: string
	contact_details: string
}

export interface UpdateCustomerResponse {
}

export interface RemoveCustomerRequest {
	customer_id: number
}

export interface RemoveCustomerResponse {
}

export interface DetailCustomerRequest {
	customer_id: number
}

export interface DetailCustomerResponse {
	customer_id: number
	customer_name: string
	country_code: string
	contact_details: string
}

export interface CreateEmployeeRequest {
	employee_photo: string
	employee_name: string
	contact_details: string
	company_id: number
	link_code: string
	work_status: number
	order_id: number
}

export interface CreateEmployeeResponse {
	employee_id: number
}

export interface UpdateEmployeeRequest {
	employee_id: number
	employee_photo: string
	employee_name: string
	contact_details: string
	company_id: number
	link_code: string
	work_status: number
	order_id: number
}

export interface UpdateEmployeeResponse {
}

export interface RemoveEmployeeRequest {
	employee_id: number
}

export interface RemoveEmployeeResponse {
}

export interface DetailEmployeeRequest {
	employee_id: number
}

export interface DetailEmployeeResponse {
	employee_id: number
	employee_photo: string
	employee_name: string
	contact_details: string
	company_id: number
	link_code: string
	work_status: number
	order_id: number
}

export interface ListEmployeeRequest {
}

export interface ListEmployeeResponse {
	items: Array<DetailEmployeeResponse>
}

export interface CreateOrderRequest {
	customer_id: number
	company_id: number
	address_id: number
	desgin_id: number
	deposite_payment: number
	deposite_date: string
	final_payment?: number
	final_payment_date?: string
	order_description?: string
	post_date: string
	reserve_date: string
	finish_date?: string
}

export interface CreateOrderResponse {
	order_id: number
}

export interface UpdateOrderRequest {
	order_id: number
	customer_id: number
	final_payment?: number
	final_payment_date?: string
	order_description: string
	reserve_date: string
	finish_date?: string
}

export interface UpdateOrderResponse {
}

export interface RemoveOrderRequest {
	order_id: number
}

export interface RemoveOrderResponse {
}

export interface DetailOrderRequest {
	order_id: number
}

export interface DetailOrderResponse {
	order_id: number
	customer_id: number
	company_id: number
	address_id: number
	desgin_id: number
	deposite_payment: number
	deposite_amount: number
	current_deposite_rate: number
	deposite_date: string
	final_payment: number
	final_amount: number
	final_payment_date: string
	total_fee: number
	order_description: string
	post_date: string
	reserve_date: string
	finish_date: string
	status: number
}

export interface ListOrderRequest {
}

export interface ListOrderResponse {
	items: Array<DetailOrderResponse>
}

export interface DetailServiceRequest {
	service_id: number
}

export interface DetailServiceResponse {
	service_id: number
	service_type: string
	service_description: string
}

export interface ListServiceRequest {
}

export interface ListServiceResponse {
	items: Array<DetailServiceResponse>
}

export interface CreateDesignRequest {
	company_id: number
	service_id: number
	price: number
	comments: string
}

export interface CreateDesignResponse {
	design_id: number
}

export interface UpdateDesignRequest {
	design_id: number
	company_id: number
	service_id: number
	price: number
	comments: string
}

export interface UpdateDesignResponse {
}

export interface RemoveDesignRequest {
	design_id: number
}

export interface RemoveDesignResponse {
}

export interface DetailDesignRequest {
	design_id: number
}

export interface DetailDesignResponse {
	design_id: number
	company_id: number
	service_id: number
	price: number
	comments: string
}

export interface ListDesignRequest {
	service_id?: number
}

export interface ListDesignResponse {
	items: Array<DetailDesignResponse>
}

export interface CreatePaymentRequest {
	card_number: string
	holder_name: string
	expiry_time: string
	security_code: string
}

export interface CreatePaymentResponse {
	payment_id: number
}

export interface UpdatePaymentRequest {
	payment_id: number
	card_number: string
	holder_name: string
	expiry_time: string
	security_code: string
}

export interface UpdatePaymentResponse {
}

export interface RemovePaymentRequest {
	payment_id: number
}

export interface RemovePaymentResponse {
}

export interface DetailPaymentRequest {
	payment_id: number
}

export interface DetailPaymentResponse {
	payment_id: number
	card_number: string
	holder_name: string
	expiry_time: string
	security_code: string
}

export interface ListPaymentRequest {
}

export interface ListPaymentResponse {
	items: Array<DetailPaymentResponse>
}

export interface CreateOperationRequest {
	employee_id: number
	order_id: number
	operation: number
	issue_date: string
}

export interface CreateOperationResponse {
	operation_id: number
}

export interface DetailOperationRequest {
	operation_id: number
}

export interface DetailOperationResponse {
	operation_id: number
	employee_id: number
	order_id: number
	operation: number
	issue_date: string
}

export interface ListOperationRequest {
}

export interface ListOperationResponse {
	items: Array<DetailOperationResponse>
}

export interface CreateEmployeeServiceRequest {
	service_id: number
}

export interface CreateEmployeeServiceResponse {
}

export interface RemoveEmployeeServiceRequest {
	employee_id: number
	service_id: number
}

export interface RemoveEmployeeServiceResponse {
}

export interface ListEmployeeServiceRequest {
	employee_id: number
}

export interface ListEmployeeServiceResponse {
	items: Array<DetailServiceResponse>
}

