// Code generated by goctl. DO NOT EDIT!

package broadcast

import (
	"fmt"
	"strconv"

	"github.com/zeromicro/go-zero/core/stores/redis"
)

var (
	cacheBBroadcastGroupIdPrefix = "cache:bBroadcast:groupId:"
)

type (
	bBroadcastModel interface {
		Insert(data *BBroadcast) (int, error)
		FindOne(groupId int64, orderId int64) (int, error)
		List(groupId int64) (*[]int64, error)
		Delete(groupId int64, orderId int64) (int, error)
		DeleteAll(groupId int64) (int, error)
	}

	defaultBBroadcastModel struct {
		conn redis.Redis
		table string
	}

	BBroadcast struct {
		GroupId int64 `db:"group_id"`
		OrderId int64 `db:"order_id"`
	}
)

func newBBroadcastModel(c redis.RedisConf) *defaultBBroadcastModel {
	return &defaultBBroadcastModel{
		conn:       *c.NewRedis(),
		table:      "`b_broadcast`",
	}
}

func (m *defaultBBroadcastModel) Insert(data *BBroadcast) (int, error) {
	bBroadcastGroupIdKey := fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, data.GroupId)
	ret, err := m.conn.Sadd(bBroadcastGroupIdKey, data.OrderId)
	return ret, err
}

func (m *defaultBBroadcastModel) FindOne(groupId int64, orderId int64) (int, error) {
	bBroadcastGroupIdKey := fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, groupId)
	ret, _, err := m.conn.Sscan(bBroadcastGroupIdKey, 0, strconv.FormatInt(orderId, 10), 1)
	
	if err != nil {
		return 0, err
	} else if len(ret) == 0 {
		return 0, ErrNotFound
	}
	return 1, nil
}

func (m *defaultBBroadcastModel) List(groupId int64) (*[]int64, error) {
	bBroadcastGroupIdKey := fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, groupId)
	ret, err := m.conn.Smembers(bBroadcastGroupIdKey)

	switch err {
	case nil:
		var resp []int64
		for _, val := range ret{
			order_id, err := strconv.ParseInt(val, 10, 64)
			if err == nil {
				resp = append(resp, order_id)
			}
		}
		return &resp, nil
	default:
		return nil, err
	}
}

func (m *defaultBBroadcastModel) Delete(groupId int64, orderId int64) (int, error) {
	bBroadcastGroupIdKey := fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, groupId)
	ret, err := m.conn.Srem(bBroadcastGroupIdKey, orderId)
	return ret, err
}

func (m *defaultBBroadcastModel) DeleteAll(groupId int64) (int, error) {
	bBroadcastGroupIdKey := fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, groupId)
	ret, err := m.conn.Del(bBroadcastGroupIdKey)
	return ret, err
}

func (m *defaultBBroadcastModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheBBroadcastGroupIdPrefix, primary)
}

func (m *defaultBBroadcastModel) tableName() string {
	return m.table
}
